# Generated by Django 4.2.5 on 2024-11-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default='Dhaka,Bangladesh'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], default='Male', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_no',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
